// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWkspmTqvj6pHxVsWKBqSqup9B9l0N-EM',
    appId: '1:699818901344:web:6b0d8b4f462f0f5d11e805',
    messagingSenderId: '699818901344',
    projectId: 'mobile-authentification',
    authDomain: 'mobile-authentification.firebaseapp.com',
    storageBucket: 'mobile-authentification.appspot.com',
    measurementId: 'G-JTH401VJ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXh2BN7wNCUURTLGN8FZBLC9BU0sVnIH4',
    appId: '1:699818901344:android:e0206fe1e982fc8a11e805',
    messagingSenderId: '699818901344',
    projectId: 'mobile-authentification',
    storageBucket: 'mobile-authentification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA_DMcfmpNVYiNus3HjzJQI3bP6dojnXU',
    appId: '1:699818901344:ios:520c32d08183583611e805',
    messagingSenderId: '699818901344',
    projectId: 'mobile-authentification',
    storageBucket: 'mobile-authentification.appspot.com',
    iosClientId: '699818901344-lqltd4m7r0vd626lhu3uh19rgcteuvuj.apps.googleusercontent.com',
    iosBundleId: 'com.gkd.mobileAuthentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA_DMcfmpNVYiNus3HjzJQI3bP6dojnXU',
    appId: '1:699818901344:ios:6d0484e0fff14f8311e805',
    messagingSenderId: '699818901344',
    projectId: 'mobile-authentification',
    storageBucket: 'mobile-authentification.appspot.com',
    iosClientId: '699818901344-4bt5cemlg8b40dc3cvu46kngqj8h3141.apps.googleusercontent.com',
    iosBundleId: 'com.gkd.mobileAuthentification.RunnerTests',
  );
}
